name: Deploy Produção

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: producao

      - name: Deploy via FTP para Produção
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST_PROD }}
          username: ${{ secrets.FTP_USER_PROD }}
          password: ${{ secrets.FTP_PASS_PROD }}
          local-dir: ./
          server-dir: /public_html/sistema/pub/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            api/credentials.php
